language: ruby
rvm:
- 2.0.0
- 2.1.0
deploy:
  provider: heroku
  api_key:
    secure: b405e76d-b842-4d88-89c0-bcf9b4367920
  run: 
    - "rake db:schema:load"
    - "rake db:migrate RAILS_ENV=staging"
    - "rake db:seed"
    - "script/delayed_job start"
  app: ontapstaging
  on:
    branch: staging
    rvm: 2.0.0
  buildpack: https://github.com/Orasi/heroku-buildpack-ruby.git
