# config/aws.yml
defaults: &defaults
  access_key_id: "AKIAJQ2M5RN5VB67QCWQ"
  secret_access_key: "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"
development:
  <<: *defaults
  bucket: "orasitest"
test:
  <<: *defaults
  bucket: "myapp-test"
production:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "myapp"
