# config/aws.yml
defaults: &defaults

  access_key_id: "124"
  secret_access_key: "1234"
staging:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "orasitest"
development:
  <<: *defaults
  bucket: "myapp-test"
test:
  <<: *defaults
  bucket: "myapp-test"

production:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "myapp"
